# Generated by Django 5.1.8 on 2025-05-01 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swotify", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="enseignant",
            name="grade",
            field=models.CharField(blank=True, default="Professeur", max_length=255),
        ),
        migrations.AddField(
            model_name="enseignant",
            name="nom",
            field=models.CharField(blank=True, default="Nom générique", max_length=255),
        ),
        migrations.AddField(
            model_name="enseignant",
            name="prenom",
            field=models.CharField(
                blank=True, default="Prénom générique", max_length=255
            ),
        ),
    ]
