# Generated by Django 5.1.8 on 2025-05-11 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swotify", "0002_enseignant_grade_enseignant_nom_enseignant_prenom"),
    ]

    operations = [
        migrations.AddField(
            model_name="comportement",
            name="positif",
            field=models.BooleanField(default=False),
        ),
    ]
