# Generated by Django 5.1.8 on 2025-05-20 08:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "swotify",
            "0004_rename_message_message_contenu_remove_message_eleve_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Paiement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("montant", models.DecimalField(decimal_places=2, max_digits=10)),
                ("date_paiement", models.DateField(auto_now_add=True)),
                ("annee_scolaire", models.CharField(max_length=20)),
                ("commentaire", models.TextField(blank=True, null=True)),
                (
                    "eleve",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="paiements",
                        to="swotify.eleve",
                    ),
                ),
            ],
        ),
    ]
