# Generated by Django 5.1.8 on 2025-05-20 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swotify", "0005_paiement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="paiement",
            old_name="montant",
            new_name="montant_verse",
        ),
        migrations.AddField(
            model_name="paiement",
            name="moyen_paiement",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
