# Generated by Django 5.1.8 on 2025-05-20 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swotify", "0006_rename_montant_paiement_montant_verse_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="frais_scolarite",
            field=models.DecimalField(decimal_places=2, default=100000, max_digits=10),
        ),
    ]
