# Generated by Django 5.1.8 on 2025-05-31 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swotify", "0007_classe_frais_scolarite"),
    ]

    operations = [
        migrations.AddField(
            model_name="classe",
            name="capacite",
            field=models.IntegerField(default=50),
        ),
    ]
