# Generated by Django 5.1.8 on 2025-06-11 15:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("swotify", "0008_classe_capacite"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"ordering": ["date_envoi"]},
        ),
        migrations.AlterField(
            model_name="classe",
            name="niveau",
            field=models.CharField(
                choices=[
                    ("T", "Terminale"),
                    ("P", "Première"),
                    ("S", "Seconde"),
                    ("6", "Sixième"),
                    ("5", "Cinquième"),
                    ("4", "Quatrième"),
                    ("3", "Troisième"),
                    ("0", "Autre"),
                ],
                default="S",
                max_length=1,
                verbose_name="Niveau",
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="destinataire",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_recus",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="expediteur",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="messages_envoyes",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
